sudo: required
services:
  - docker

before_install:
  - docker build -t brianjanker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brianjanker/react-test npm test

after_success:
  - docker build -t brianjanker/multi-client ./client
  - docker build -t brianjanker/multi-nginx ./nginx
  - docker build -t brianjanker/multi-server ./server
  - docker build -t brianjanker/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push brianjanker/multi-client
  - docker push brianjanker/multi-nginx
  - docker push brianjanker/multi-server
  - docker push brianjanker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multi-Docker-env
  bucket_name: elasticbeanstalk-us-east-2-730180557028
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY